### PR TITLE
Add meta component

### PR DESCRIPTION
**Pull request by ricky-lau**
An example of meta component (Original Article | 9 October 2019):

Screen Shot 2019-10-15 at 14 22 00

### CODE REVIEW

**Comment by jpw** [comment]
meta made me think META tags, maybe a more descriptive name might be an idea?

**Comment by ricky-lau** [comment]
`c-meta-indicator`, `c-content-meta`, `c-content-description`, `c-descriptor`...? Open to suggestions 😁 

@davidpauljunior might affect you if you decide to use this for Nature 150 👀

**Comment by davidpauljunior** [comment]
I don't think any of the suggested names make it clearer.
This is a component in a toolkit, there's no way it could be related to `<meta>` tags IMO.

**Comment by davidpauljunior** [comment]
`metadata` _maybe_ but <shrug>

**Comment by ricky-lau** [comment]
Inclined to keep it as it is then. Can revisit if we find that this naming is too confusing when used.

**Pull request merged**
