### PR TITLE
Added listing component

### PR DESCRIPTION
**Pull request by ricky-lau**
**Example of listing with text and image:**
Screen Shot 2019-10-15 at 14 52 55

**Example of listing in a search result:**
Screen Shot 2019-10-15 at 14 54 33

### CODE REVIEW

**Comment by benjclark** [comment]
the only issue here is that the listing with text and image looks like its the same component as c-springer-media?
https://github.com/springernature/frontend-springer-toolkit/tree/master/packages/springer-media

**Comment by davidpauljunior** [comment]
Yeah these are different components IMO.
Listing is 1 component, and `card` is the other.  `media` will be changed to `card` at some point.

**Comment by benjclark** [comment]
@davidpauljunior  help me out then... what's the difference?
c-springer-media
Screenshot 2019-10-16 at 10 58 53

c-listing
Screenshot 2019-10-16 at 10 59 11

**Comment by benjclark** [comment]
@davidpauljunior @ricky-lau  oh, and i've just seen we've created the same thing again c-teaser 😂 


c-teaser
Screenshot 2019-10-16 at 11 05 32

**Comment by davidpauljunior** [comment]
This is just temporary hacks. 
It's going to be 1 to rule them all. `c-card c-card--row`.

**Comment by benjclark** [comment]
@davidpauljunior  Ah ok, so `c-springer-media`, `c-springer-listing` and `c-springer-teaser` are all going to get refactored in to `c-card` some time soon?

**Comment by ricky-lau** [comment]
Was having a quick chat with David earlier and I think we agreed to differentiate `c-listing` as content that is automated whereas `c-media/card` is something that is curated or more call-to-actiony. 

I do agree that visually they look similar at the moment. I'm going to add a brief update to the description for listing to try and highlight what this should be for.

**Comment by benjclark** [comment]
I think the most important thing is that if a new person joined right now they would be able to work out which one to use for the design they have.

If a new person doesn't know which one to use because they appear to be the same thing then we've gone wrong in my opinion.

If a design came in for data that can be rendered automatically AND curated by business people which would you use?

**Comment by davidpauljunior** [comment]
Cards are generic, listings are specific.
What you put in a card is entirely up to you, but it's very generic.
Generally they're used to make something stand out a bit.

**Comment by davidpauljunior** [comment]
If you end up with a single component that does all of it then it because very confusing and different products will end up with code that they don't need.

**Comment by davidpauljunior** [comment]
I also thing that if images are in listings they should be very small

**Comment by benjclark** [comment]
Ok, I still don't really get it, but hopefully I'll understand as time goes on. Definitely worth spending time on the README of each component to give clear advice when and why to use. As long as I can easily decide which one should be used when a design comes in that matches them then I'm happy.

**Comment by davidpauljunior** [comment]
I had thoughts on this, let's discuss in person.
This can be merged methinks.

**Pull request merged**
